defaults: &defaults
  host: localhost

development:
  <<: *defaults
  database: digruby_development

test: &test
  <<: *defaults
  database: digruby_test

cucumber:
  <<: *test

# set these environment variables on your prod server
production:
  <<: *defaults
<% if ENV["MONGOHQ_URL"] %>
  uri: <%= ENV['MONGOHQ_URL'] %>
<% else %>
  host: localhost
  database: digruby_production
<% end %>

