defaults: &defaults
  host: localhost
  allow_dynamic_fields: true
  parameterize_keys: true
  persist_in_safe_mode: true
  raise_not_found_error: true
  reconnect_time: 3
  use_object_ids: false

development:
  <<: *defaults
  database: digruby_development

test:
  <<: *defaults
  database: digruby_test

# set these environment variables on your prod server
production:
  <<: *defaults
  uri: <%= ENV['MONGOHQ_URL'] %>


